/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#012d1d",
        "on-background": "#1c1b1b",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#274e3d",
        "on-secondary": "#ffffff",
        "surface-tint": "#3f6653",
        "on-secondary-fixed-variant": "#0e5138",
        "primary-fixed": "#c1ecd4",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-container": "#d29895",
        "tertiary-fixed-dim": "#f5b7b4",
        "tertiary-fixed": "#ffdad8",
        "on-primary-container": "#86af99",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#aeeecb",
        "on-primary-fixed": "#002114",
        "on-surface-variant": "#414844",
        "surface-container": "#f0eded",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#002114",
        "surface-dim": "#dcd9d9",
        "surface-container-low": "#f6f3f2",
        "surface-container-highest": "#e5e2e1",
        "surface-bright": "#fcf9f8",
        "on-secondary-container": "#316e52",
        "outline-variant": "#c1c8c2",
        "on-surface": "#1c1b1b",
        "tertiary": "#401b1b",
        "secondary-fixed-dim": "#95d4b3",
        "inverse-primary": "#a5d0b9",
        "on-tertiary": "#ffffff",
        "secondary": "#2c694e",
        "surface": "#fcf9f8",
        "outline": "#717973",
        "primary-fixed-dim": "#a5d0b9",
        "on-tertiary-fixed-variant": "#673a39",
        "error": "#ba1a1a",
        "surface-variant": "#e5e2e1",
        "secondary-fixed": "#b1f0ce",
        "surface-container-high": "#eae7e7",
        "tertiary-container": "#5a302f",
        "primary-container": "#1b4332",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#331111",
        "inverse-surface": "#313030",
        "background": "#fcf9f8"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.5rem", "lg": "1rem", "xl": "1.25rem", "full": "9999px"},
    },
  },
  plugins: [],
}

